# Configures the Dart analyzer for static code analysis, checking errors,
# warnings, and enforcing lints in Flutter projects.

include: package:flutter_lints/flutter.yaml

# Custom lint rules
linter:
  rules:
    # Code style
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - avoid_redundant_argument_values
    - avoid_setters_without_getters
    - avoid_single_cascade_in_expression_statements
    - cascade_invocations
    - join_return_with_assignment
    - prefer_foreach
    - prefer_if_elements_to_conditional_expressions
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - use_string_buffers
    - require_trailing_commas

    # Performance
    - avoid_unnecessary_containers
    - unnecessary_statements

    # Error handling
    - always_put_control_body_on_new_line
    - prefer_asserts_with_message
    - throw_in_finally

    # Flutter specific
    - sized_box_for_whitespace
    - use_decorated_box

    # Pub specific
    - sort_pub_dependencies

    # Formatting
    - lines_longer_than_80_chars
    - curly_braces_in_flow_control_structures

    # Design
    - avoid_print

    # Usage
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_slow_async_io
    - invariant_booleans
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - test_types_in_equals
    - unnecessary_await_in_return
    - use_to_and_as_if_applicable
    - always_use_package_imports

analyzer:
  exclude:
    - lib/gen/**                # Generated files
    - lib/**.g.dart             # All .g.dart files
    - lib/**.freezed.dart       # Freezed generated files

# For more information on configuring the analyzer:
# https://dart.dev/guides/language/analysis-options