name: magic_password
description: "A simple password manager app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  crypto: any
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^2.0.14
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_theme_plus: ^6.6.4
  logger: ^2.4.0
  lottie: ^3.1.3
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/icons/social_medias/
    - assets/images/
    - assets/jsons/
    - assets/translations/
    - assets/jsons/themes/

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/magic_password.png"
  windows:
    generate: true
    image_path: "assets/images/magic_password.png"
  macos:
    generate: true
    image_path: "assets/images/magic_password.png"
  image_path: "assets/images/magic_password.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/magic_password.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/magic_password.png"
#  background_image: "assets/images/magic_password.png"
#  background_image_dark: "assets/images/magic_password.png"
  fullscreen: false
  android: true
  ios: true
  web: true
  color_dark_android: "#FFFFFF"
  color_dark_ios: "#FFFFFF"
  ios_content_mode: scaleAspectFit
  android_12:
    color: "#FFFFFF"
    image: "assets/images/magic_password.png"
    color_dark: "#FFFFFF"
    color_dark_android: "#FFFFFF"
  android_gravity: center