name: magic_password
description: "A simple password manager app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  encrypt: ^5.0.3
  crypto: any
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1
  flutter_secure_storage: ^4.2.1
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/jsons/

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/magic_password.png"
  windows:
    generate: true
    image_path: "assets/images/magic_password.png"
  macos:
    generate: true
    image_path: "assets/images/magic_password.png"
  image_path: "assets/images/magic_password.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/magic_password.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/magic_password.png"
#  background_image: "assets/images/magic_password.png"
#  background_image_dark: "assets/images/magic_password.png"
  fullscreen: false
  android: true
  ios: true
  web: true
  color_dark_android: "#FFFFFF"
  color_dark_ios: "#FFFFFF"
  ios_content_mode: scaleAspectFit
  android_12:
    color: "#FFFFFF"
    image: "assets/images/magic_password.png"
    color_dark: "#FFFFFF"
    color_dark_android: "#FFFFFF"
  android_gravity: center