// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfJQh1plZqzOPtBX_BCPZZJ5FrPY0Gxrc',
    appId: '1:1058226922760:web:cc4a5c14e99e8955e538bd',
    messagingSenderId: '1058226922760',
    projectId: 'magic-password-2a82c',
    authDomain: 'magic-password-2a82c.firebaseapp.com',
    storageBucket: 'magic-password-2a82c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwACQU8tMbKmwg6rMVstUjJb4GqUdjpsc',
    appId: '1:1058226922760:android:bb2ffa9934e5c629e538bd',
    messagingSenderId: '1058226922760',
    projectId: 'magic-password-2a82c',
    storageBucket: 'magic-password-2a82c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALJxqmGwu3AaHgMEkFDF50Vc0dYE6yET4',
    appId: '1:1058226922760:ios:f4fe2f9794075e02e538bd',
    messagingSenderId: '1058226922760',
    projectId: 'magic-password-2a82c',
    storageBucket: 'magic-password-2a82c.firebasestorage.app',
    iosBundleId: 'com.quyetnv.magicPassword',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALJxqmGwu3AaHgMEkFDF50Vc0dYE6yET4',
    appId: '1:1058226922760:ios:f4fe2f9794075e02e538bd',
    messagingSenderId: '1058226922760',
    projectId: 'magic-password-2a82c',
    storageBucket: 'magic-password-2a82c.firebasestorage.app',
    iosBundleId: 'com.quyetnv.magicPassword',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfJQh1plZqzOPtBX_BCPZZJ5FrPY0Gxrc',
    appId: '1:1058226922760:web:3c15a8e1319d4107e538bd',
    messagingSenderId: '1058226922760',
    projectId: 'magic-password-2a82c',
    authDomain: 'magic-password-2a82c.firebaseapp.com',
    storageBucket: 'magic-password-2a82c.firebasestorage.app',
  );
}
